config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get 'search', to: 'search#index'
  get 'about', to: 'about#index'

  resources :games, only: [:index, :show] do
    resources :characters, only: [:index, :show]
    resources :bosses, only: [:index, :show]
    resources :items, only: [:index, :show]
  end

  resources :characters, only: [:index, :show]
  resources :bosses, only: [:index, :show]
  resources :items, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bosses_controller.rb
class BossesController < ApplicationController
  def index
    response = ZeldaApiService.new.fetch_bosses
    @bosses = response['data']

    @bosses = Kaminari.paginate_array(@bosses).page(params[:page]).per(10)
  end

  def show
    @boss = fetch_boss(params[:id])
  end

  private

  def fetch_boss(id)
    response = ZeldaApiService.new.fetch_boss(id)
    response['data']
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    response = ZeldaApiService.new.fetch_characters
    @characters = response['data']

    @characters = Kaminari.paginate_array(@characters).page(params[:page]).per(10)
  end

  def show
    @character = fetch_character(params[:id])
  end

  private

  def fetch_character(id)
    response = ZeldaApiService.new.fetch_character(id)
    response['data']
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    response = ZeldaApiService.new.fetch_games
    @games = response['data']

    @games = Kaminari.paginate_array(@games).page(params[:page]).per(10)
  end

  def show
    @game = fetch_game(params[:id])
  end

  private

  def fetch_game(id)
    response = ZeldaApiService.new.fetch_game(id)
    response['data']
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    response = ZeldaApiService.new.fetch_items
    @items = response['data']

    @items = Kaminari.paginate_array(@items).page(params[:page]).per(10)
  end

  def show
    @item = fetch_item(params[:id])
  end

  private

  def fetch_item(id)
    response = ZeldaApiService.new.fetch_item(id)
    response['data']
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = params[:query]
    @category = params[:category]

    case @category
    when 'games'
      response = ZeldaApiService.new.fetch_games
      @results = response['data'].select { |game| game['name'].downcase.include?(@query.downcase) }
    when 'characters'
      response = ZeldaApiService.new.fetch_characters
      @results = response['data'].select { |character| character['name'].downcase.include?(@query.downcase) }
    when 'bosses'
      response = ZeldaApiService.new.fetch_bosses
      @results = response['data'].select { |boss| boss['name'].downcase.include?(@query.downcase) }
    when 'items'
      response = ZeldaApiService.new.fetch_items
      @results = response['data'].select { |item| item['name'].downcase.include?(@query.downcase) }
    else
      @results = []
    end

    @results = Kaminari.paginate_array(@results).page(params[:page]).per(10)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bosses_helper.rb
module BossesHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/about/index.html.erb
<div class="mt-8 h-screen my-auto">
  <h1 class="text-2xl font-bold mb-4">About Zelda API Data Project</h1>
  <div class="bg-white rounded shadow p-4">
    <h2 class="text-xl font-bold">Data Source</h2>
    <p>The Zelda API provides detailed data on games, characters, bosses, and items from the Zelda universe, structured in JSON format. Each dataset includes specific fields such as names, descriptions, and unique IDs. For example, the games dataset include fields like name, description, developer, and release date. The data will be displayed on dedicated pages within a web application, allowing users to explore detailed information about each category.</p>
    <br>
    <h2 class="text-xl font-bold">Usage in the Project</h2>
    <p>To store and manage this data, we will create database tables for 4 categories: games, characters, bosses, and items. The relationships between different datasets will be maintained by storing related game IDs in the respective tables. This structure allows for things such as viewing all games an item appears in or the characters encountered in a specific game.</p>
    <br>
    <h2 class="text-xl font-bold">Database ERD</h2>
    <%= image_tag("zelda_erd.png", alt: "Database ERD for Zelda API", class: "mt-4 rounded-lg shadow-md") %>
  </div>
</div>

app/views/bosses/index.html.erb
<div class="mt-8 h-screen my-auto">
  <h1 class="text-2xl font-bold mb-4">Bosses</h1>

  <div class="grid grid-cols-1 gap-4">
    <% @bosses.each do |boss| %>
      <div class="bg-white rounded shadow p-4">
        <h2 class="text-xl font-bold">
        <%= link_to boss['name'], boss_path(boss['id']) %>
        </h2>
      </div>
    <% end %>
  </div>

  <%= paginate @bosses %>
</div>

app/views/bosses/show.html.erb
<div class="mt-8 h-screen my-auto">
  <h1 class="text-2xl font-bold mb-4"><%= @boss['name'] %></h1>

  <div class="bg-white rounded shadow p-4">
    <p><strong>Description:</strong> <%= @boss['description'] %></p>
    
    <% if @boss['appearances'].present? %>
      <p>
        <%= link_to 'Games: ', games_path, class: 'font-bold hover:underline' %>
        <% first_game = true %>
        <% @boss['appearances'].each do |game_url| %>
          <% game_id = game_url.split('/').last %>
          <% game_response = ZeldaApiService.new.fetch_game(game_id) %>
          <% game_name = game_response['data']['name'] if game_response['success'] %>
          
          <% if game_name %>
            <% unless first_game %>, <% end %>
            <% first_game = false %>
            <% game_link = game_path(game_id) %>
            <%= link_to game_name, game_link, class: 'text-blue-500 hover:underline' %>
          <% end %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/characters/index.html.erb
<div class="mt-8 h-screen my-auto">
  <h1 class="text-2xl font-bold mb-4">Characters</h1>

  <div class="grid grid-cols-1 gap-4">
    <% @characters.each do |character| %>
      <div class="bg-white rounded shadow p-4">
        <h2 class="text-xl font-bold">
        <%= link_to character['name'], character_path(character['id']) %>
        </h2>
      </div>
    <% end %>
  </div>

  <%= paginate @characters %>
</div>

app/views/characters/show.html.erb
<div class="mt-8 h-screen my-auto">
  <h1 class="text-2xl font-bold mb-4"><%= @character['name'] %></h1>

  <div class="bg-white rounded shadow p-4">
    <p><strong>Description:</strong> <%= @character['description'] %></p>
    
    <% if @character['appearances'].present? %>
      <p>
        <%= link_to 'Games: ', games_path, class: 'font-bold hover:underline' %>
        <% first_game = true %>
        <% @character['appearances'].each do |game_url| %>
          <% game_id = game_url.split('/').last %>
          <% game_response = ZeldaApiService.new.fetch_game(game_id) %>
          <% game_name = game_response['data']['name'] if game_response['success'] %>
          
          <% if game_name %>
            <% unless first_game %>, <% end %>
            <% first_game = false %>
            <% game_link = game_path(game_id) %>
            <%= link_to game_name, game_link, class: 'text-blue-500 hover:underline' %>
          <% end %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/games/index.html.erb
<div class="mt-8 h-screen my-auto">
  <h1 class="text-2xl font-bold mb-4">Games</h1>

  <div class="grid grid-cols-1 gap-4">
    <% @games.each do |game| %>
      <div class="bg-white rounded shadow p-4">
        <h2 class="text-xl font-bold">
        <%= link_to game['name'], game_path(game['id']) %>
        </h2>
      </div>
    <% end %>
  </div>

  <%= paginate @games %>
</div>

app/views/games/show.html.erb
<div class="mt-8 h-screen my-auto">
  <h1 class="text-2xl font-bold mb-4"><%= @game['name'] %></h1>

  <div class="bg-white rounded shadow p-4">
    <p><strong>Description:</strong> <%= @game['description'] %></p>
    <p><strong>Developer:</strong> <%= @game['developer'] %></p>
    <p><strong>Publisher:</strong> <%= @game['publisher'] %></p>
    <p><strong>Released Date:</strong> <%= @game['released_date'] %></p>
  </div>
</div>

app/views/home/index.html.erb
<div class="flex justify-center items-center h-screen my-auto">
  <div class="max-w-4xl mx-auto p-6 bg-white rounded shadow-lg">
    <h1 class="text-4xl font-bold mb-4">Categories</h1>
    
    <div class="grid grid-cols-1 gap-4">
      <div class="p-4 bg-lime-500 text-white rounded-lg shadow">
        <%= link_to 'Games', games_path, class: 'text-xl font-semibold hover:underline' %>
      </div>
      <div class="p-4 bg-lime-500 text-white rounded-lg shadow">
        <%= link_to 'Characters', characters_path, class: 'text-xl font-semibold hover:underline' %>
      </div>
      <div class="p-4 bg-lime-500 text-white rounded-lg shadow">
        <%= link_to 'Bosses', bosses_path, class: 'text-xl font-semibold hover:underline' %>
      </div>
      <div class="p-4 bg-lime-500 text-white rounded-lg shadow">
        <%= link_to 'Items', items_path, class: 'text-xl font-semibold hover:underline' %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="mt-8 h-screen my-auto">
  <h1 class="text-2xl font-bold mb-4">Items</h1>

  <div class="grid grid-cols-1 gap-4">
    <% @items.each do |item| %>
      <div class="bg-white rounded shadow p-4">
        <h2 class="text-xl font-bold">
        <%= link_to item['name'], item_path(item['id']) %>
        </h2>
      </div>
    <% end %>
  </div>

  <%= paginate @items %>
</div>

app/views/items/show.html.erb
<div class="mt-8 h-screen my-auto">
  <h1 class="text-2xl font-bold mb-4"><%= @item['name'] %></h1>

  <div class="bg-white rounded shadow p-4">
    <p><strong>Description:</strong> <%= @item['description'] %></p>
    
    <% if @item['games'].present? %>
      <p>
        <%= link_to 'Games: ', games_path, class: 'font-bold hover:underline' %>
        <% first_game = true %>
        <% @item['games'].each do |game_url| %>
          <% game_id = game_url.split('/').last %>
          <% game_response = ZeldaApiService.new.fetch_game(game_id) %>
          <% game_name = game_response['data']['name'] if game_response['success'] %>
        
          <% if game_name %>
            <% unless first_game %>, <% end %>
            <% first_game = false %>
            <% game_link = game_path(game_id) %>
            <%= link_to game_name, game_link, class: 'text-blue-500 hover:underline' %>
          <% end %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Zelda API Data Project</title>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body class="bg-image min-h-screen">
    <nav class="bg-lime-500 p-6">
      <div class="container mx-auto flex justify-between items-center">
        <%= image_tag("zelda_icon.png", alt: "The Legend of Zelda Triforce Logo", size: "100", class: "mt-4 rounded-lg shadow-md") %>
        <div class="text-white text-xl font-bold">Zelda API Data Project</div>
        <ul class="flex space-x-4">
          <li><%= link_to 'Home', root_path, class: 'text-white hover:underline' %></li>
          <li><%= link_to 'Games', games_path, class: 'text-white hover:underline' %></li>
          <li><%= link_to 'Characters', characters_path, class: 'text-white hover:underline' %></li>
          <li><%= link_to 'Bosses', bosses_path, class: 'text-white hover:underline' %></li>
          <li><%= link_to 'Items', items_path, class: 'text-white hover:underline' %></li>
          <li><%= link_to 'About', about_path, class: 'text-white hover:underline' %></li>
        </ul>
        <%= form_with url: search_path, method: :get, local: true, class: 'flex space-x-2' do |form| %>
          <%= form.text_field :query, value: params[:query], placeholder: 'Search...', class: 'p-4 shadow' %>
          <%= form.select :category, options_for_select([['Games', 'games'], ['Characters', 'characters'], ['Bosses', 'bosses'], ['Items', 'items']], selected: params[:category]), class: 'p-4 shadow' %>
          <%= form.submit 'Search', class: 'p-4 bg-yellow-500 text-white shadow border' %>
        <% end %>
      </div>
    </nav>

    <div class="container mx-auto mt-8">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/search/index.html.erb
<div class="mt-8 h-screen my-auto">
  <h1 class="text-2xl font-bold mb-4">Search Results for '<%= @query %>' in <%= @category.capitalize %></h1>

  <% if @results.any? %>
    <div class="grid grid-cols-1 gap-4">
      <% @results.each do |result| %>
        <div class="bg-white rounded shadow p-4">
          <h2 class="text-xl font-bold">
            <% if @category == 'games' %>
              <%= link_to result['name'], game_path(result['id']) %>
            <% elsif @category == 'characters' %>
              <%= link_to result['name'], character_path(result['id']) %>
            <% elsif @category == 'bosses' %>
              <%= link_to result['name'], boss_path(result['id']) %>
            <% elsif @category == 'items' %>
              <%= link_to result['name'], item_path(result['id']) %>
            <% end %>
          </h2>
        </div>
      <% end %>
    </div>

    <div class="mt-4">
      <%= paginate @results %>
    </div>
  <% else %>
    <p>No results found.</p>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-lime-500 text-white py-4">
  <div class="container mx-auto flex justify-between items-center">
    <p>&copy; <%= Time.now.year %> Cedric Sumaoang. Project for RRC Polytech. All rights reserved.</p>
    <nav>
      <ul class="flex space-x-4">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</footer>